### ISSUE TITLE
Adjazenzmatrix der Landkreise

### ISSUE THREAD

**Issue by StefanAugsburg** [RadMagnus/herausforderung_1591#29]
Erstelle eine csv Liste mit:
In jeder Zeile AGS,(0,0,...)
Dabei  ist (0,0,...) eine Liste mit 401 Einträgen (Landkreise+kreisfreie Städte), einer 1 falls Eintrag x benachbart ist, eine 0 falls nicht (natürlich ohne Klammern ;) )

**Comment by robbyHuelsi** [comment]
Die Überlegung aktuell ist eher weg von der Adjazenzmatrix zu einer Entfernungsmatrix. Weil einfacher herzustellen und präzieser
